Class BD_WeaponHelpHandler : EventHandler {
	ui bool ShowWeapHelp;
    override void consoleProcess(ConsoleEvent e) {
		if (e.name != "BD_ShowWeapHelp")
			return;
		if (bdoom_weapons != 0) {
			ShowWeapHelp = !ShowWeapHelp;
			if (ShowWeapHelp)
				S_StartSound("menu/showhelp",CHAN_AUTO,volume:0.5);
			else
				S_StartSound("menu/hidehelp",CHAN_AUTO,volume:0.5);
		}
		else {			
			ShowWeapHelp = false;
		}
    }
    override void renderOverlay(RenderEvent e) {
        if (ShowWeapHelp) {
			if (bdoom_weapons < 1)
				return;
			PlayerInfo player	= players[consoleplayer];
			PlayerPawn mo		= player.mo;
			if (!player || !player.readyweapon || !mo)
				return;			
            let weap = player.readyWeapon.GetClassName();
			if (!weap)
				return;
			if (bdoom_weapons < 1)
				return;
			string title;
			string	desc;
			string note;
			int mainofs = 50;
			int statofs1 = 1000;
			int statofs2 = 1270;
			int yofs = 180;
			int fillheight = 420;
			if (bdoom_weapons == 1) {
				string attack1;	string atkrate1;	string damage1;	string type1;	string prspeed1; string blastarea1;
				string attack2;	string atkrate2;	string damage2;	string type2;	string prspeed2; string blastarea2;
				switch (weap) {
					case 'BD_Fist' : 
					title 		= Stringtable.Localize("$BDH_Fist");
					desc		= Stringtable.Localize("$BDH_EFist_Desc");
					attack1 	= Stringtable.Localize("$BDH_Punch");		atkrate1 = String.Format("2.5 %s",Stringtable.Localize("$BDH_hitssec"));
					damage1 	= "2-20";		type1 		= Stringtable.Localize("$BDH_Melee");
					attack2 	= Stringtable.Localize("$BDH_Kick");		atkrate2 = String.Format("1.6 %s",Stringtable.Localize("$BDH_hitssec"));
					damage2 	= "15-36";		type2 		= type1;
					note		= Stringtable.Localize("$BDH_EFist_Note");
					break;
					
					case 'BD_Chainsaw' : 
					title 		= Stringtable.Localize("$BDH_Chainsaw");
					desc		= Stringtable.Localize("$BDH_EChainsaw_Desc");
					attack1 	= Stringtable.Localize("$BDH_ESawAttack");	atkrate1 	= String.Format("8.75 %s",Stringtable.Localize("$BDH_hitssec"));
					damage1 	= "2-20";		type1 		= Stringtable.Localize("$BDH_Melee");
					break;
					
					case 'BD_Pistol' : 
					if (mo.CountInv('BD_Pistol') <= 1) {
						title 		= Stringtable.Localize("$BDH_Pistol");
						desc		= Stringtable.Localize("$BDH_EPistol_Desc");
						attack1 	= Stringtable.Localize("$BDH_FirePistol");		atkrate1 	= String.Format("2.9 %s",Stringtable.Localize("$BDH_shotssec"));
						damage1 	= "5-15";	type1 		= Stringtable.Localize("$BDH_Hitscan");
						note		= Stringtable.Localize("$BDH_EPistol_Note");
					}
					else {
						title 		= Stringtable.Localize("$BDH_Pistols");
						desc		= Stringtable.Localize("$BDH_Pistols");
						attack1 	= Stringtable.Localize("$BDH_Fire1Pistol");	atkrate1 	= String.Format("2.9 %s",Stringtable.Localize("$BDH_shotssec"));	
						damage1 	= "5-15";	type1 		= Stringtable.Localize("$BDH_Hitscan");
						attack2 	= Stringtable.Localize("$BDH_DualFire");		atkrate2 	= String.Format("5.8 %s",Stringtable.Localize("$BDH_shotssec"));	
						damage2 	= "5-15";	type2 		= type1;
						note		= Stringtable.Localize("$BDH_PistolsNote");
					}
					break;
					
					case 'BD_Shotgun' : 
					title 		= Stringtable.Localize("$BDH_Shotgun");
					desc		= Stringtable.Localize("$BDH_EShotgun_Desc");
					attack1 	= Stringtable.Localize("$BDH_FireShotgun");;		atkrate1 	= String.Format("0.94 %s",Stringtable.Localize("$BDH_shotssec"));	
					damage1 	= "35-105 (7 x 5-15)";	type1 		= Stringtable.Localize("$BDH_Hitscan");
					attack2 	= "Buttstock melee";	atkrate2 	= String.Format("1.3 %s",Stringtable.Localize("$BDH_hitssec"));		
					damage2 	= "18-36 (42-252 with Berserk)";	type2 		= Stringtable.Localize("$BDH_Melee");
					note		= Stringtable.Localize("$BDH_EShotgun_Note");
					break;
					
					case 'BD_SuperShotgun' : 
					title 		= Stringtable.Localize("$BDH_SSG");
					desc		= Stringtable.Localize("$BDH_ESSG_Desc");
					attack1 	= Stringtable.Localize("$BDH_SSGFire2");		atkrate1 	= String.Format("0.61 %s",Stringtable.Localize("$BDH_shotssec"));	
					damage1 	= "100-300 (20 x 5-15)";	type1 		= Stringtable.Localize("$BDH_Hitscan");
					attack2 	= Stringtable.Localize("$BDH_SSGFire1");		atkrate2 	= String.Format("3.5 %s",Stringtable.Localize("$BDH_shotssec"));
					damage2 	= "50-150 (10 x 5-15)";		type2 		= type1;
					note		= Stringtable.Localize("$BDH_ESSG_Note");
					break;
					
					case 'BD_Chaingun' : 
					title 		= Stringtable.Localize("$BDH_Chaingun");
					desc		= Stringtable.Localize("$BDH_Chaingun_Desc");
					attack1 	= Stringtable.Localize("$BDH_ChaingunFire");	atkrate1 	= String.Format("8.75 %s",Stringtable.Localize("$BDH_shotssec"));	
					damage1 	= "5-15";	type1 		= Stringtable.Localize("$BDH_Hitscan");
					attack2 	= Stringtable.Localize("$BDH_RapidFire");		atkrate2 	= String.Format("17.5 %s",Stringtable.Localize("$BDH_shotssec"));	
					damage2 	= damage1;	type2 		= type1;
					note		= Stringtable.Localize("$BDH_Chaingun_Note");
					break;
					
					case 'BD_RocketLauncher' : 
					title 		= Stringtable.Localize("$BDH_RLaun");
					desc		= Stringtable.Localize("$BDH_ERLaun_Desc");
					attack1 	= Stringtable.Localize("$BDH_FireRocket");		atkrate1 	= String.Format("2.33 %s",Stringtable.Localize("$BDH_shotssec"));
					damage1 	= String.Format("20-160 + 128 (%s + %s)",Stringtable.Localize("$BDH_impact"),Stringtable.Localize("$BDH_blast"));
					type1 		= String.Format("%s, %s, %s", Stringtable.Localize("$BDH_Projectile"), Stringtable.Localize("$BDH_explosive"), Stringtable.Localize("$BDH_linear"));
					prspeed1	= "20";		blastarea1 = "128";
					attack2 	= Stringtable.Localize("$BDH_FireHoming");		atkrate2 	= String.Format("0.94 %s",Stringtable.Localize("$BDH_shotssec"));	
					damage2 	= damage1;	
					type2 		= String.Format("%s, %s, %s", Stringtable.Localize("$BDH_Projectile"), Stringtable.Localize("$BDH_explosive"), Stringtable.Localize("$BDH_homing"));
					prspeed2	= "17";		blastarea2 = blastarea1;
					break;
					
					case 'BD_PlasmaRifle' : 
					title 		= Stringtable.Localize("$BDH_Plasma");
					desc		= Stringtable.Localize("$BDH_EPlasma_desc");
					attack1 	= Stringtable.Localize("$BDH_FirePlasma");;		atkrate1 	= String.Format("11.67 %s",Stringtable.Localize("$BDH_shotssec"));	
					damage1 	= "5-40";		type1 	= String.Format("%s, %s", Stringtable.Localize("$BDH_Projectile"), Stringtable.Localize("$BDH_linear")); prspeed1	= "25";
					attack2 	= Stringtable.Localize("$BDH_FireRailgun");		atkrate2 	= String.Format("0.81 %s",Stringtable.Localize("$BDH_shotssec"));	
					damage2 	= "250-625";	type2 	= String.Format("%s, %s", Stringtable.Localize("$BDH_Railgun"), Stringtable.Localize("$BDH_nonpiercing"));
					note		= Stringtable.Localize("$BDH_EPlasma_note");
					break;
					
					case 'BD_BFG9000' : 
					title 		= Stringtable.Localize("$BDH_BFG");
					desc		= Stringtable.Localize("$BDH_EBFG_Desc");
					attack1 	= Stringtable.Localize("$BDH_FireBFG");			atkrate1 	= String.Format("0.87 %s",Stringtable.Localize("$BDH_shotssec"));	
					damage1 	= "100-800 + 40x???";
					type1 		= String.Format("%s, %s, %s", Stringtable.Localize("$BDH_Projectile"), Stringtable.Localize("$BDH_linear"), Stringtable.Localize("$BDH_tracing")); prspeed1	= "25";
					attack2 	= Stringtable.Localize("$BDH_FireRailgun");		atkrate2 	= Stringtable.Localize("$BDH_Continuous");	
					damage2 	= String.Format("%s 700/%s", Stringtable.Localize("$BDH_approx"), Stringtable.Localize("$BDH_sec"));	
					type2 		= String.Format("%s, %s", Stringtable.Localize("$BDH_Railgun"), Stringtable.Localize("$BDH_piercing"));
					note		= Stringtable.Localize("$BDH_EBFG_Note");
					break;
				}
				if (prspeed1)		fillheight += 20;
				if (blastarea1)	fillheight += 20;
				if (prspeed2)		fillheight += 20;
				if (blastarea2)	fillheight += 20;
				if (!note && !attack2)	fillheight -= 150;
				BD_StatusBarScreen.Fill("404040",30,80,1850,fillheight, 0.85);
				if (attack1) {
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Primary"),		(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5));
					BD_StatusBarScreen.DrawString("UNRLC",attack1,			(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5));
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_AtkRate"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5));
					BD_StatusBarScreen.DrawString("UNRLC",atkrate1,		(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5));
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Damage"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5));
					BD_StatusBarScreen.DrawString("UNRLC",damage1,			(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5));
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Type"),			(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5));
					BD_StatusBarScreen.DrawString("UNRLC",type1,			(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5));
				}	
				if (prspeed1) {
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_ProjSpeed"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5));
					BD_StatusBarScreen.DrawString("UNRLC",prspeed1,		(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5));
				}
				if (blastarea1) {
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BlastArea"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5));
					BD_StatusBarScreen.DrawString("UNRLC",blastarea1,		(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5));
				}
				if (attack2) {
					yofs += 50;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Secondary"),		(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5));
					BD_StatusBarScreen.DrawString("UNRLC",attack2,			(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5));
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_AtkRate"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5));
					BD_StatusBarScreen.DrawString("UNRLC",atkrate2,		(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5));
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Damage"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5));
					BD_StatusBarScreen.DrawString("UNRLC",damage2,			(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5));
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Type"),			(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5));
					BD_StatusBarScreen.DrawString("UNRLC",type2,			(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5));
				}
				if (prspeed2) {
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_ProjSpeed"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5));
					BD_StatusBarScreen.DrawString("UNRLC",prspeed2,		(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5));
				}
				if (blastarea2) {
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BlastArea"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5));
					BD_StatusBarScreen.DrawString("UNRLC",blastarea2,		(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5));
				}
			}
			else if (bdoom_weapons == 2) {
				switch (weap) {
					case 'BD_Fist' : 
					fillheight += 30;
					BD_StatusBarScreen.Fill("404040",30,80,1850,fillheight, 0.85);
					title = Stringtable.Localize("$BDH_CQC");
					desc = Stringtable.Localize("$BDH_MFist_Desc");
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Primary"),	(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_CQC_LPunch"),	(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_AtkRate"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("%s 4.3 %s",Stringtable.Localize("$BDH_upto"),Stringtable.Localize("$BDH_hitssec")),		
																										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Damage"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","6-24",									(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 50;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Secondary"),	(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_CQC_RPunch"),	(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);	
					yofs += 30*4;				
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Damage"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","15-52",									(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 50;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Kick"),		(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_CQC_Kick"),	(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);	
					yofs += 30;				
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Damage"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","30-55",									(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					note = Stringtable.Localize("$BDH_MFist_Note");
					break;
					
					case 'BD_Chainsaw' : 
					fillheight += 90;
					BD_StatusBarScreen.Fill("404040",30,80,1850,fillheight, 0.85);
					title = Stringtable.Localize("$BDH_Chainsaw");
					desc = Stringtable.Localize("$BDH_MChainsaw_Desc");
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Primary"),	(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_MSawAttack"),	(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_AtkRate"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("17.5 %s",Stringtable.Localize("$BDH_hitssec")),		
																										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Damage"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","6-24",									(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Type"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("%s, %s",Stringtable.Localize("$BDH_Melee"),Stringtable.Localize("$BDH_hstunlock")),	
																										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 50;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Secondary"),	(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_MSawAlt"),	(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
																			
					yofs += 50;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Any"),		(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_MSawPull"),	(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);	
					
					note = Stringtable.Localize("$BDH_MChainsaw_Note");
					break;
					
					case 'BD_Pistol' : 
					BD_StatusBarScreen.Fill("404040",30,80,1850,fillheight, 0.85);
					title = Stringtable.Localize("$BDH_Pistol");
					desc = Stringtable.Localize("$BDH_MPistol_Desc");		
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Magazine"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","15",										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_ReloadTime"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("1.29 %s",Stringtable.Localize("$BDH_sec")),		
																										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);

					yofs += 50;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Primary"),	(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("%s (%s)",Stringtable.Localize("$BDH_FirePistol"),Stringtable.Localize("$BDH_semiauto")),
																										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_FireRate"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("%s 8.75 %s",Stringtable.Localize("$BDH_upto"),Stringtable.Localize("$BDH_shotssec")),
																										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BaseDamage"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","15",										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Type"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("%s, %s",Stringtable.Localize("$BDH_Bullet"),Stringtable.Localize("$BDH_medfalloff")),
																										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BestRange"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","< 512",									(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);

					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BulletSpeed"),(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","170",										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);					
					break;
					
					case 'BD_Shotgun' : 
					BD_StatusBarScreen.Fill("404040",30,80,1850,fillheight, 0.85);
					title = Stringtable.Localize("$BDH_Shotgun");
					desc = Stringtable.Localize("$BDH_MShotgun_Desc");			
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Magazine"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","8",				(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_ReloadTime"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_MFireRate"),		
																										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);

					yofs += 50;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Primary"),	(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("%s (%s)",Stringtable.Localize("$BDH_FireShotgun"),Stringtable.Localize("$BDH_semiauto")),
																			(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_FireRate"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("%s 1.3 %s",Stringtable.Localize("$BDH_upto"),Stringtable.Localize("$BDH_shotssec")),
																			(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BaseDamage"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","12 x 7",		(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Type"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("%s, %s",Stringtable.Localize("$BDH_Pellet"),Stringtable.Localize("$BDH_highfalloff")),			
																										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BestRange"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","< 400",									(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);

					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_PelletSpeed"),(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","140",										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);	

					note = Stringtable.Localize("$BDH_MShotgun_Note");
					break;
					
					case 'BD_SuperShotgun' : 
					fillheight += 100;
					BD_StatusBarScreen.Fill("404040",30,80,1850,fillheight, 0.85);
					title = Stringtable.Localize("$BDH_MSSG");
					desc = Stringtable.Localize("$BDH_MSSG_Desc");
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Magazine"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","2",				(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_ReloadTime"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_MSSG_Reload"),		
																			(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);

					yofs += 50;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Primary"),	(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_SSGFire2"),
																			(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Secondary"),	(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_SSGFire1"), 	(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
																			
					yofs += 60;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BaseDamage"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_MSSG_Damage"),(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Type"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("%s, %s,\n%s", Stringtable.Localize("$BDH_Pellet"), Stringtable.Localize("$BDH_piercing"), Stringtable.Localize("$BDH_vhighfalloff")),
																										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 30*2;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BestRange"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","< 300",									(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);

					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_PelletSpeed"),(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","140",										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);	

					note = Stringtable.Localize("$BDH_MSSG_Note");
					break;
					
					case 'BD_Chaingun' : 
					fillheight += 100;
					BD_StatusBarScreen.Fill("404040",30,80,1850,fillheight, 0.85);
					title = Stringtable.Localize("$BDH_Rifle");
					desc = Stringtable.Localize("$BDH_Rifle_Desc");		
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Magazine"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","40",				(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);					
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_ReloadTime"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_RifleReload"),		
																			(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);

					yofs += 50;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Primary"),		(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_RiflePrimary"),
																			(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
																			
					yofs += 30*2;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_FireRate"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC", String.Format(Stringtable.Localize("$BDH_RifleFirerate"),Stringtable.Localize("$BDH_shotssec"),Stringtable.Localize("$BDH_shotssec")),		
																			(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
																			
					yofs += 40*2;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Secondary"),		(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_RifleSecondary"), (statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
																			
					yofs += 60;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BaseDamage"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","15",				(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Type"),			(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("%s, %s", Stringtable.Localize("$BDH_Bullet"),Stringtable.Localize("$BDH_lowfalloff")),			
																											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BestRange"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","< 640",			(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);

					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BulletSpeed"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","230",											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);	

					note = Stringtable.Localize("$BDH_Rifle_Note");
					break;
					
					case 'BD_RocketLauncher' : 
					fillheight += 100;
					BD_StatusBarScreen.Fill("404040",30,80,1850,fillheight, 0.85);
					title = Stringtable.Localize("$BDH_MRLaun");
					desc = 	Stringtable.Localize("$BDH_MRLaun_Desc");		
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Magazine"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","8",											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);					
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_ReloadTime"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("1.89 %s",Stringtable.Localize("$BDH_sec")),		
																											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);

					yofs += 50;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Primary"),		(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_FireRocket"),
																											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Type"),			(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("%s, %s, %s", Stringtable.Localize("$BDH_Projectile"), Stringtable.Localize("$BDH_explosive"), Stringtable.Localize("$BDH_linear")),		
																											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_ProjSpeed"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("25 (%s) / 51.8 (%s)", Stringtable.Localize("$BDH_initial"), Stringtable.Localize("$BDH_max")),	
																											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
																			
					yofs += 40;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Secondary"),		(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_FireGrenade"), 	(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Type"),			(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("%s, %s, %s", Stringtable.Localize("$BDH_Projectile"), Stringtable.Localize("$BDH_explosive"), Stringtable.Localize("$BDH_bouncing")),		
																											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_ProjSpeed"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("25 (%s)",Stringtable.Localize("$BDH_initial")),
																											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
																			
					yofs += 60;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Damage"),			(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("20-160 + 128 (%s + %s)",Stringtable.Localize("$BDH_impact"),Stringtable.Localize("$BDH_blast")),				
																											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BlastArea"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","128",											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);					
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_FireRate"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("%s 1.75 %s",Stringtable.Localize("$BDH_upto"),Stringtable.Localize("$BDH_hitssec")),			
																											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					note = Stringtable.Localize("$BDH_MRLaun_note");
					break;
					
					case 'BD_PlasmaRifle' : 
					fillheight += 60;
					BD_StatusBarScreen.Fill("404040",30,80,1850,fillheight, 0.85);
					title = Stringtable.Localize("$BDH_Plasma");
					desc = Stringtable.Localize("$BDH_MPlasma_desc");		

					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Primary"),		(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_FirePlasma"),
																											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_FireRate"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("8.75 %s",Stringtable.Localize("$BDH_shotssec")),
																											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Damage"),			(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","30",											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BlastArea"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","40",											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Type"),			(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("%s, %s, %s", Stringtable.Localize("$BDH_Projectile"), Stringtable.Localize("$BDH_explosive"), Stringtable.Localize("$BDH_linear")),	
																											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 40;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Secondary"),		(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_MCooldown"), 		(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Duration"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("0.06-0.57 %s",Stringtable.Localize("$BDH_sec")),
																											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					
					note = Stringtable.Localize("$BDH_MPlasma_note");
					break;
					
					case 'BD_BFG9000' : 
					statofs2 = 1320;
					fillheight += 210;					
					BD_StatusBarScreen.Fill("404040",30,80,1850,fillheight, 0.85);
					title = Stringtable.Localize("$BDH_BFG");
					desc = Stringtable.Localize("$BDH_MBFG_Desc");	

					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_Primary"),		(statofs1,yofs),translation:Font.CR_ORANGE,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_FireMBFG"),		(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30*2;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_FireRate"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC",String.Format("0.5-1.1 %s",Stringtable.Localize("$BDH_shotssec")),
																											(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_OrbDamage"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","60-480",										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_OrbArea"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","92-288",										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BeamDamage"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","52–206",										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_BeamRange"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","256-1280",									(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_NumberTargets"),	(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC","6-14",										(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					yofs += 30*2;
					BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_ProjSpeed"),		(statofs1,yofs),translation:Font.CR_GREEN,scale:(1.5,1.5),linespacing:10);
					BD_StatusBarScreen.DrawString("UNRLC", String.Format(Stringtable.Localize("$BDH_BFGProjSpeed"), Stringtable.Localize("$BDH_initial")),	(statofs2,yofs),translation:Font.CR_GOLD,scale:(1.5,1.5),linespacing:10);
					
					
					note = Stringtable.Localize("$BDH_MBFG_Note");
					break;
				}
			}
			BD_StatusBarScreen.DrawString("MM2FONTO",title,			(mainofs,100),translation:Font.CR_ORANGE,scale:(1.5,1.5));
			BD_StatusBarScreen.DrawString("UNRLC",desc, 				(mainofs,180),translation:Font.CR_GREY,scale:(1.5,1.5),linespacing:10);
			BD_StatusBarScreen.DrawString("MM2FONTO","STATS", 			(statofs1+300,100),translation:Font.CR_GREY,scale:(1.5,1.5),linespacing:10);
			if (note) {
				BD_StatusBarScreen.DrawString("UNRLC","NOTES:",		(mainofs,330),translation:Font.CR_GREEN,scale:(1.5,1.5));
				BD_StatusBarScreen.DrawString("UNRLC",note,				(mainofs,370),translation:Font.CR_GREY,scale:(1.5,1.5),linespacing:10);
			}
			BD_StatusBarScreen.Fill("04ac33",30,80,800,4,0.85);				//top left
			BD_StatusBarScreen.Fill("04ac33",1080,80,800,4,0.85);				//top right
			BD_StatusBarScreen.Fill("04ac33",30,fillheight+76,1850,4,0.85);	//bottom
			BD_StatusBarScreen.Fill("04ac33",30,82,4,fillheight-6,0.85);		//left
			BD_StatusBarScreen.Fill("04ac33",1876,82,4,fillheight-6,0.85);	//right
			BD_StatusBarScreen.Fill("04ac33",980,100,4,fillheight-32,0.4);	//middle
			BD_StatusBarScreen.DrawString("UNRLC",Stringtable.Localize("$BDH_WEAPONINFO"),		(837, 70),translation:Font.CR_GREEN,scale:(1.5,1.5));
        }
    }
}