//***************************\\
//***************************\\
//****** O B J E C T S ******\\
//***************************\\
//***************************\\

//// EXPLOSIVE BARREL

Class EBarrelPiece : BasicMetalPiece
{
Default {
	scale 0.5;
	}
override void GibBeginPlay()
	{
	sprite = GetSpriteIndex("BPRT");
	brot = random(14,20)*randompick(-1,1);
	A_QueueCorpse();
	roll = random(0,359);
	}
override void GibFall() 
	{
	if (waterlevel == 0) {
		A_Scream();
		}
	A_SetMass(bmass);
	bMISSILE = false;
	bNOINTERACTION = true;
	bRELATIVETOFLOOR = true;
	bMOVEWITHSECTOR = true;
	}
}

Class BD_ExplosiveBarrel : ExplosiveBarrel replaces ExplosiveBarrel
{
Flare_General flare;
override void PostBeginPlay() {
	super.PostBeginPlay();
	flare = Flare_General(Spawn("Flare_General",(pos.x,pos.y,pos.z+26)));
	if (!flare)
		return;
	flare.scale.x = 0.2;
	flare.scale.y = 0.14;
	flare.fcolor = 'green';
	}
override void Tick() {
	super.Tick();
	if (!flare)
		return;
	if (bdoom_flames) {
		flare.SetOrigin((pos.x,pos.y,pos.z+26),true);
		flare.A_SetRenderstyle(0.4,Style_Add);
		}
	else
		flare.A_SetRenderstyle(0.4,Style_None);
	}
states
	{
	Spawn:
		BAR1 ABCDCB 4;
		loop;
	Death:
		TNT1 A 0 {
			if (flare)
				flare.destroy();
			}
		BEXP AABBC 1;
		BEXP C 1 A_Scream;
		TNT1 A 0 {
			A_SprayDecal("BarrelScorch",128);
			if (bdoom_debris) {
			
				}
			if (bdoom_debris) {
				for (int i = 12; i > 0; i--)
					A_SpawnItemEx("SmokingPiece",	frandom(-6,6),frandom(-6,6),frandom(4,24),	frandom(-5,5),frandom(-5,5),frandom(7,12),failchance:64);
				for (int i = 6; i > 0; i--)
					A_SpawnItemEx("EBarrelPiece",	frandom(-6,6),frandom(-6,6),frandom(4,24),	frandom(-10,10),frandom(-10,10),frandom(8,15),failchance:64);
				}
			}
		BEXP DE 2;
		TNT1 A 0 A_SetRenderstyle(0.8,Style_ADD);
		BEXP FFGGH 1;
		BEXP H 1 {
			A_Explode();
			if (bdoom_shakes)
				Radius_Quake(3,15,0,5,0);
			}
		BEXP IJKLMNOPQ 3;
		TNT1 A 1050 A_BarrelDestroy;
		TNT1 A 5 {
			A_SetRenderstyle(1.0,Style_Normal);
			A_Respawn();
			}
		wait;
	}
}

/*
Actor BarrelPart : DebrisGeneral
{
+DOOMBOUNCE
-NOGRAVITY
-NOBLOCKMAP
gravity 1.0
seesound ""
scale .55
mass 1
states
	{
	Spawn:
		TNT1 A 0 NoDelay A_QueueCorpse
		TNT1 A 0 A_SetScale(scalex*randompick(-1,1),scaley)
		BPRT ABCDEFGH 1 
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Debris")==0,"Null")
		goto spawn+2
	Death:
	   	TNT1 A 0 A_jump(256,1,2,3)
		BPRT A 50 A_JumpIf(GetCVAR("bdoom_Debris")==0,"Null")
		wait
		BPRT B 50 A_JumpIf(GetCVAR("bdoom_Debris")==0,"Null")
		wait
		BPRT E 50 A_JumpIf(GetCVAR("bdoom_Debris")==0,"Null")
		wait
	}
}


//******
// HELL
//******



Actor BD_EvilEye replaces EvilEye
{
+NOINTERACTION
states
	{
	Spawn:
		TNT1 A 0 NoDelay A_spawnitem("BD_Candlestick")
		TNT1 A 0 A_spawnitem("FloatingEye",0,10)
		stop
	}
}

Actor FloatingEye
{
renderstyle translucent
+VISIBILITYPULSE
+FORCEXYBILLBOARD
+SOLID
+NOGRAVITY
+RELATIVETOFLOOR
+FLOATBOB
floatbobstrength .75
states
	{
	Spawn:
		SEYE ABCDEF 4 bright
		loop
	}
}

Actor BD_FloatingSkull : FloatingSkull replaces FloatingSkull
{
+FLOATBOB
floatbobstrength 0.5
states
	{
	Spawn:
		TNT1 A 0 NoDelay A_CheckSight(3)
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Flames")==0,2)
		TNT1 A 0 A_SpawnItemEx("FirePiece",random(-10,10),random(-10,10),random(56,60),	0,0,1,0)
		FSKX A 4 bright
		TNT1 A 0 A_CheckSight(3)
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Flames")==0,2)
		TNT1 A 0 A_SpawnItemEx("FirePiece",random(-10,10),random(-10,10),random(56,60),	0,0,1,0)
		FSKX B 4 bright
		TNT1 A 0 A_CheckSight(3)
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Flames")==0,2)
		TNT1 A 0 A_SpawnItemEx("FirePiece",random(-10,10),random(-10,10),random(56,60),	0,0,1,0)
		FSKX C 4 bright
		TNT1 A 0 A_CheckSight(3)
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Flames")==0,2)
		TNT1 A 0 A_SpawnItemEx("FirePiece",random(-10,10),random(-10,10),random(56,60),	0,0,1,0)
		FSKX D 4 bright
		TNT1 A 0 A_CheckSight(3)
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Flames")==0,2)
		TNT1 A 0 A_SpawnItemEx("FirePiece",random(-10,10),random(-10,10),random(56,60),	0,0,1,0)
		FSKX E 4 bright
		TNT1 A 0 A_CheckSight(3)
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Flames")==0,2)
		TNT1 A 0 A_SpawnItemEx("FirePiece",random(-10,10),random(-10,10),random(56,60),	0,0,1,0)
		FSKX F 4 bright
		TNT1 A 0 A_CheckSight(3)
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Flames")==0,2)
		TNT1 A 0 A_SpawnItemEx("FirePiece",random(-10,10),random(-10,10),random(56,60),	0,0,1,0)
		FSKX A 4 bright
		goto Spawn
	}
}

Actor SkullSmoke : DebrisGeneral
{
bouncetype None
+NOGRAVITY
+DONTSPLASH
+NOINTERACTION
renderstyle ADD
alpha 0.5
scale .04
states
	{
	Spawn:
		SPRK A 1 bright A_FadeOut(0.03)
		TNT1 A 0 A_SetScale(scalex*0.9,scaley*0.9)
		loop
	}
}

actor BD_HeartColumn : HeartColumn replaces HeartColumn
{
states
	{
	Spawn:
		COL5 B 14
		TNT1 A 0 A_CheckSight(2)
		TNT1 A 0 A_SpawnItemEx("DecorativeBloodDrop",0,0,random(32,36),	random(1,2),0,random(1,3),	random(-0,360),	0,200)
		COL5 A 9 
		loop
	}
}

Actor DecorativeBloodDrop : BD_Blood
{
states	
	{
	Death:
		stop
	}
}

Actor BD_BigTree : BigTree replaces BigTree
{
states
	{
	Spawn:
		TNT1 A 0 NoDelay A_SetScale(scalex*randompick(-1,1),scaley)
		TNT1 A 0 A_Jump(256,1,2,3,4)
		TRE2 A -1
		stop
		TRE2 B -1
		stop
		TRE2 C -1
		stop
		TRE2 D -1
		stop
	}
}

Actor BD_TorchTree : TorchTree replaces TorchTree
{
states
	{
	Spawn:
		TNT1 A 0 NoDelay A_SetScale(scalex*randompick(-1,1),scaley)
		TNT1 A 0 A_Jump(256,1,2)
		TRE1 A -1
		stop
		TRE1 B -1
		stop
	}
}


//// TELEPORT FOG

Actor BD_TeleportFog : TeleportFog replaces TeleportFog
{
+FORCEXYBILLBOARD
renderstyle Add
alpha .8
states
	{
	Spawn:
		TNT1 A 0 NoDelay A_SetScale(scalex*randompick(-1,1),scaley)
		TNT1 A 0 A_SpawnItem("TeleportGreenFlare", 0, 28)		
		TFOG ABCDCBABABCDCDEFGHIJ 3 bright
		stop
	}
}

Actor TeleportGreenFlare : Flare_General
{
+FORCEXYBILLBOARD
states
	{
	Spawn:
		TNT1 A 0 NoDelay A_JumpIf(GetCVAR("bdoom_Flames")==0,"Null")
		TNT1 A 0 A_Jump(256,1,2,3)
		LENG A 3 bright
		LENG A 3 bright A_SetScale(0.37,0.37)
		LENG A 3 bright A_SetScale(0.35,0.35)
		LENG A 3 bright
		LENG A 3 bright A_SetScale(0.37,0.37)
		LENG A 3 bright A_SetScale(0.35,0.35)
		LENG A 3 bright
		LENG A 3 bright A_SetScale(0.37,0.37)
		LENG A 3 bright A_SetScale(0.35,0.35)
		LENG A 3 bright
		LENG A 3 bright A_SetScale(0.37,0.37)
		LENG A 3 bright A_SetScale(0.35,0.35)
		LENG A 3 bright
		LENG A 3 bright A_SetScale(0.37,0.37)
		LENG A 3 bright A_SetScale(0.35,0.35)
		LENG A 3 bright A_SetScale(0.3,0.3)
		LENG A 3 bright A_SetScale(0.25,0.25)
		LENG A 3 bright A_SetScale(0.2,0.2)
		LENG A 3 bright A_SetScale(0.1,0.1)
		stop
	}
}