//***************************\\
//***************************\\
//****** O B J E C T S ******\\
//***************************\\
//***************************\\

//// EXPLOSIVE BARREL

Class EBarrelPiece : SmallDebris
{
Default {
	DebrisGeneral.sfxtype "debris";
	}
override void PostBeginPlay() {
	super.PostBeginPlay();
	wrot = random(16,24)*randompick(-1,1);
	scale *= frandom(0.8,1);
	}
states
	{
	Spawn:
		BPRT AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 {
			scale *= 0.93;
			roll+=wrot;
			}
		stop;
	}
}

Class BD_ExplosiveBarrel : ExplosiveBarrel replaces ExplosiveBarrel
{
Default {
	scale 0.8;
	deathsound "world/ebarrel";
	}
BD_BaseFlare flare;

override void Tick() {
	super.Tick();
	if (level.isFrozen())
		return;
	if (!flare && bdoom_flames && health > 0) {
		flare = BD_BaseFlare(Spawn("BD_BaseFlare",(pos.x,pos.y,pos.z+26)));
		flare.scale.x = 0.15;
		flare.scale.y = 0.11;
		flare.fcolor = 'green';
		flare.A_SetRenderstyle(0.3,Style_Add);
		}
	if (bdoom_flames && flare)
		flare.SetOrigin((pos.x,pos.y,pos.z+26),true);
	if (!bdoom_flames && flare)
		flare.destroy();
	}
states
	{
	Spawn:
		TNT1 A 0 NoDelay A_Jump(256,1,2,3,4,5);
	Idle:
		BAR0 ABCDE random(3,5) {
			if (bdoom_flames && frandom(0,10) > 7) {
				let fpart = BD_FireParticle(Spawn("BD_FireParticle",(pos.x+frandom(-5,5),pos.y+frandom(-5,5),pos.z+frandom(27.5,29))));
				fpart.vel = (0,0,frandom(0.1,0.2));
				fpart.fcolor = 'green';
				}
			}
		loop;
	Death:
		TNT1 A 0 {
			if (flare)
				flare.destroy();
			if (bdoom_shakes)
				Radius_Quake(2,15,0,5,0);
			A_SetScale(1.0);
			}
		BEXP AABBC 1;
		BEXP C 1 A_Scream;
		TNT1 A 0 {
			let bar = Spawn("ExplodedBarrel",pos);
			bar.master = self;
			A_SetRenderstyle(0.8,Style_ADD);
			scale *= frandom(0.7,1);
			scale.x *= randompick(-1,1);
			A_SprayDecal("BarrelScorch",128);			
			if (bdoom_debris) {
				for (int i = 5; i > 0; i--)
					A_SpawnItemEx("SmokingPiece",	frandom(-6,6),frandom(-6,6),frandom(4,24),	frandom(-5,5),frandom(-5,5),frandom(7,12),failchance:64);
				for (int i = 7; i > 0; i--)
					A_SpawnItemEx("EBarrelPiece",	frandom(-6,6),frandom(-6,6),frandom(4,24),	frandom(-10,10),frandom(-10,10),frandom(8,15),failchance:64);
				}
			}
		BEXP DE 2 {
			if (bdoom_debris)
				A_SpawnItemEx("BigBlackSmoke",	frandom(-6,6),frandom(-6,6),frandom(16,56),	frandom(-0.4,0.4),frandom(-0.4,0.4),frandom(0.8,2.2),failchance:32);
			}
		BEXP FFGGH 1 {
			if (bdoom_debris)
				A_SpawnItemEx("BigBlackSmoke",	frandom(-6,6),frandom(-6,6),frandom(16,56),	frandom(-0.4,0.4),frandom(-0.4,0.4),frandom(0.8,2.2),failchance:32);
			}
		BEXP H 1 A_Explode();
		BEXP IJKLMNOPQ 3 {
			if (bdoom_debris)
				A_SpawnItemEx("BigBlackSmoke",	frandom(-6,6),frandom(-6,6),frandom(16,56),	frandom(-0.4,0.4),frandom(-0.4,0.4),frandom(0.8,2.2),failchance:32);
			}
		TNT1 A 1050 A_BarrelDestroy;
		TNT1 A 5 {
			A_SetRenderstyle(1.0,Style_Normal);
			A_SetScale(0.8);
			A_Respawn();
			A_RemoveChildren(true,RMVF_EVERYTHING);
			}
		wait;
	}
}

Class ExplodedBarrel : Actor
{
//int timer;
Default {
	+NOINTERACTION
	+MOVEWITHSECTOR
	+RELATIVETOFLOOR
	scale 0.8;
	}
static const string SSprite[] =
	{
		"BAR2","BAR3","BAR4"
	};
/*override void Tick() {
	super.tick();
	if (level.IsFrozen() || !bdoom_debris)
		return;
	timer++;
	if (random(0,10) > 9 && timer >= 20) {
		for (int i = random(1,3); i > 0; i--)
			A_SpawnItemEx("BlackSmoke",frandom(-8,8),frandom(-8,8),frandom(6,8),0,0,frandom(0.2,0.6),failchance:(128));
		timer = 0;
		}
	}*/
states
	{
	Loadsprites:
		BAR2 ABCDE 0;
		BAR3 ABCDE 0;
		BAR4 ABCDE 0;
	Spawn:
		TNT1 A 0 NoDelay { sprite = GetSpriteIndex(SSprite[random(0,2)]); }
	Idle:
		#### A random(35,200);
		#### ABCDEDCB random(6,9);
		loop;
	}
}

/*

//******
// HELL
//******



Actor BD_EvilEye replaces EvilEye
{
+NOINTERACTION
states
	{
	Spawn:
		TNT1 A 0 NoDelay A_spawnitem("BD_Candlestick")
		TNT1 A 0 A_spawnitem("FloatingEye",0,10)
		stop
	}
}

Actor FloatingEye
{
renderstyle translucent
+VISIBILITYPULSE
+FORCEXYBILLBOARD
+SOLID
+NOGRAVITY
+RELATIVETOFLOOR
+FLOATBOB
floatbobstrength .75
states
	{
	Spawn:
		SEYE ABCDEF 4 bright
		loop
	}
}

Actor BD_FloatingSkull : FloatingSkull replaces FloatingSkull
{
+FLOATBOB
floatbobstrength 0.5
states
	{
	Spawn:
		TNT1 A 0 NoDelay A_CheckSight(3)
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Flames")==0,2)
		TNT1 A 0 A_SpawnItemEx("FirePiece",random(-10,10),random(-10,10),random(56,60),	0,0,1,0)
		FSKX A 4 bright
		TNT1 A 0 A_CheckSight(3)
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Flames")==0,2)
		TNT1 A 0 A_SpawnItemEx("FirePiece",random(-10,10),random(-10,10),random(56,60),	0,0,1,0)
		FSKX B 4 bright
		TNT1 A 0 A_CheckSight(3)
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Flames")==0,2)
		TNT1 A 0 A_SpawnItemEx("FirePiece",random(-10,10),random(-10,10),random(56,60),	0,0,1,0)
		FSKX C 4 bright
		TNT1 A 0 A_CheckSight(3)
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Flames")==0,2)
		TNT1 A 0 A_SpawnItemEx("FirePiece",random(-10,10),random(-10,10),random(56,60),	0,0,1,0)
		FSKX D 4 bright
		TNT1 A 0 A_CheckSight(3)
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Flames")==0,2)
		TNT1 A 0 A_SpawnItemEx("FirePiece",random(-10,10),random(-10,10),random(56,60),	0,0,1,0)
		FSKX E 4 bright
		TNT1 A 0 A_CheckSight(3)
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Flames")==0,2)
		TNT1 A 0 A_SpawnItemEx("FirePiece",random(-10,10),random(-10,10),random(56,60),	0,0,1,0)
		FSKX F 4 bright
		TNT1 A 0 A_CheckSight(3)
		TNT1 A 0 A_JumpIf(GetCVAR("bdoom_Flames")==0,2)
		TNT1 A 0 A_SpawnItemEx("FirePiece",random(-10,10),random(-10,10),random(56,60),	0,0,1,0)
		FSKX A 4 bright
		goto Spawn
	}
}

Actor SkullSmoke : DebrisGeneral
{
bouncetype None
+NOGRAVITY
+DONTSPLASH
+NOINTERACTION
renderstyle ADD
alpha 0.5
scale .04
states
	{
	Spawn:
		SPRK A 1 bright A_FadeOut(0.03)
		TNT1 A 0 A_SetScale(scalex*0.9,scaley*0.9)
		loop
	}
}

actor BD_HeartColumn : HeartColumn replaces HeartColumn
{
states
	{
	Spawn:
		COL5 B 14
		TNT1 A 0 A_CheckSight(2)
		TNT1 A 0 A_SpawnItemEx("DecorativeBloodDrop",0,0,random(32,36),	random(1,2),0,random(1,3),	random(-0,360),	0,200)
		COL5 A 9 
		loop
	}
}

Actor DecorativeBloodDrop : BD_Blood
{
states	
	{
	Death:
		stop
	}
}

Actor BD_BigTree : BigTree replaces BigTree
{
states
	{
	Spawn:
		TNT1 A 0 NoDelay A_SetScale(scalex*randompick(-1,1),scaley)
		TNT1 A 0 A_Jump(256,1,2,3,4)
		TRE2 A -1
		stop
		TRE2 B -1
		stop
		TRE2 C -1
		stop
		TRE2 D -1
		stop
	}
}

Actor BD_TorchTree : TorchTree replaces TorchTree
{
states
	{
	Spawn:
		TNT1 A 0 NoDelay A_SetScale(scalex*randompick(-1,1),scaley)
		TNT1 A 0 A_Jump(256,1,2)
		TRE1 A -1
		stop
		TRE1 B -1
		stop
	}
}


//// TELEPORT FOG

Actor BD_TeleportFog : TeleportFog replaces TeleportFog
{
+FORCEXYBILLBOARD
renderstyle Add
alpha .8
states
	{
	Spawn:
		TNT1 A 0 NoDelay A_SetScale(scalex*randompick(-1,1),scaley)
		TNT1 A 0 A_SpawnItem("TeleportGreenFlare", 0, 28)		
		TFOG ABCDCBABABCDCDEFGHIJ 3 bright
		stop
	}
}

Actor TeleportGreenFlare : Flare_General
{
+FORCEXYBILLBOARD
states
	{
	Spawn:
		TNT1 A 0 NoDelay A_JumpIf(GetCVAR("bdoom_Flames")==0,"Null")
		TNT1 A 0 A_Jump(256,1,2,3)
		LENG A 3 bright
		LENG A 3 bright A_SetScale(0.37,0.37)
		LENG A 3 bright A_SetScale(0.35,0.35)
		LENG A 3 bright
		LENG A 3 bright A_SetScale(0.37,0.37)
		LENG A 3 bright A_SetScale(0.35,0.35)
		LENG A 3 bright
		LENG A 3 bright A_SetScale(0.37,0.37)
		LENG A 3 bright A_SetScale(0.35,0.35)
		LENG A 3 bright
		LENG A 3 bright A_SetScale(0.37,0.37)
		LENG A 3 bright A_SetScale(0.35,0.35)
		LENG A 3 bright
		LENG A 3 bright A_SetScale(0.37,0.37)
		LENG A 3 bright A_SetScale(0.35,0.35)
		LENG A 3 bright A_SetScale(0.3,0.3)
		LENG A 3 bright A_SetScale(0.25,0.25)
		LENG A 3 bright A_SetScale(0.2,0.2)
		LENG A 3 bright A_SetScale(0.1,0.1)
		stop
	}
}